# -*- coding: utf-8 -*-
# generated by wxGlade 0.6.3 on Wed Feb 25 01:00:34 2009

import wx

# begin wxGlade: dependencies
# end wxGlade

# begin wxGlade: extracode

# end wxGlade

class MainFrame(wx.Frame):
    def __init__(self, *args, **kwds):
        # begin wxGlade: MainFrame.__init__
        kwds["style"] = wx.DEFAULT_FRAME_STYLE
        wx.Frame.__init__(self, *args, **kwds)
        self.HorizontalSplitter = wx.SplitterWindow(self, -1, style=wx.SP_3D|wx.SP_BORDER)
        self.InfoTabs = wx.Notebook(self.HorizontalSplitter, -1, style=wx.NB_LEFT)
        self.VerticleSpitter = wx.SplitterWindow(self.HorizontalSplitter, -1, style=wx.SP_3D|wx.SP_BORDER)
        self.PackageGroupTabs = wx.Notebook(self.VerticleSpitter, -1, style=0)
        
        # Tool Bar
        self.MainWindow_toolbar = wx.ToolBar(self, -1, style=wx.TB_HORIZONTAL|wx.TB_TEXT|wx.TB_NOICONS)
        self.SetToolBar(self.MainWindow_toolbar)
        self.MainWindow_toolbar.AddLabelTool(wx.NewId(), "Reload", wx.NullBitmap, wx.NullBitmap, wx.ITEM_NORMAL, "", "")
        self.MainWindow_toolbar.AddLabelTool(wx.NewId(), "Mark All Upgrades", wx.NullBitmap, wx.NullBitmap, wx.ITEM_NORMAL, "", "")
        self.MainWindow_toolbar.AddLabelTool(wx.NewId(), "Apply", wx.NullBitmap, wx.NullBitmap, wx.ITEM_NORMAL, "", "")
        self.MainWindow_toolbar.AddSeparator()
        self.MainWindow_toolbar.AddLabelTool(wx.NewId(), "Properties", wx.NullBitmap, wx.NullBitmap, wx.ITEM_NORMAL, "", "")
        self.MainWindow_toolbar.AddSeparator()
        self.MainWindow_toolbar.AddLabelTool(wx.NewId(), "Search", wx.NullBitmap, wx.NullBitmap, wx.ITEM_NORMAL, "", "")
        # Tool Bar end
        self.RepoList = wx.ListBox(self.PackageGroupTabs, -1, choices=[])
        self.GroupList = wx.ListBox(self.PackageGroupTabs, -1, choices=[])
        self.StatusList = wx.ListBox(self.PackageGroupTabs, -1, choices=[])
        self.list_ctrl_1 = wx.ListCtrl(self.VerticleSpitter, -1, style=wx.LC_REPORT|wx.SUNKEN_BORDER)
        self.InfoTextView = wx.TextCtrl(self.InfoTabs, -1, "", style=wx.TE_MULTILINE|wx.TE_READONLY|wx.TE_LINEWRAP)
        self.FeedbackTextView = wx.TextCtrl(self.InfoTabs, -1, "", style=wx.TE_MULTILINE|wx.TE_READONLY|wx.TE_LINEWRAP)
        self.FileTreeView = wx.TreeCtrl(self.InfoTabs, -1, style=wx.TR_HAS_BUTTONS|wx.TR_NO_LINES|wx.TR_DEFAULT_STYLE|wx.SUNKEN_BORDER)
        self.DependListView = wx.ListBox(self.InfoTabs, -1, choices=[])

        self.__set_properties()
        self.__do_layout()
        # end wxGlade

    def __set_properties(self):
        # begin wxGlade: MainFrame.__set_properties
        self.SetTitle("The Shwaurtz Package Manager")
        self.MainWindow_toolbar.SetToolBitmapSize((16, 15))
        self.MainWindow_toolbar.SetMargins((0, 0))
        self.MainWindow_toolbar.SetToolPacking(1)
        self.MainWindow_toolbar.SetToolSeparation(5)
        self.MainWindow_toolbar.Realize()
        self.list_ctrl_1.SetMinSize((495, 352))
        self.VerticleSpitter.SetMinSize((677, 352))
        self.InfoTabs.SetMinSize((677, 179))
        self.HorizontalSplitter.SetMinSize((679, 564))
        # end wxGlade

    def __do_layout(self):
        # begin wxGlade: MainFrame.__do_layout
        Sizer = wx.BoxSizer(wx.VERTICAL)
        self.PackageGroupTabs.AddPage(self.RepoList, "Repo")
        self.PackageGroupTabs.AddPage(self.GroupList, "Groups")
        self.PackageGroupTabs.AddPage(self.StatusList, "Status")
        self.VerticleSpitter.SplitVertically(self.PackageGroupTabs, self.list_ctrl_1)
        self.InfoTabs.AddPage(self.InfoTextView, "Information")
        self.InfoTabs.AddPage(self.FeedbackTextView, "Feedback")
        self.InfoTabs.AddPage(self.FileTreeView, "Files")
        self.InfoTabs.AddPage(self.DependListView, "Dependencies")
        self.HorizontalSplitter.SplitHorizontally(self.VerticleSpitter, self.InfoTabs)
        Sizer.Add(self.HorizontalSplitter, 1, wx.EXPAND, 0)
        self.SetSizer(Sizer)
        Sizer.Fit(self)
        self.Layout()
        # end wxGlade

# end of class MainFrame


