# -*- coding: utf-8 -*-
# generated by wxGlade 0.6.3 on Thu Feb 26 00:58:59 2009

import wx

# begin wxGlade: dependencies
# end wxGlade

# begin wxGlade: extracode
import sys
sys.path.append("../")
import manager
from PackageList import PackageList
from InfoTextView import InfoTextView
from RepoList import RepoList
# end wxGlade

class MainFrame(wx.Frame):
    def __init__(self, *args, **kwds):
        self.queue = []
        self.filter = [0,""]
        package1 = manager.Package("3ddesktop","extra","0.2.9-2","a 3d virtual desktop switcher (opengl/mesa)","66 KiB")
        package2 = manager.Package("6tunnel","community","0.11rc2-3","Tunnels IPv6 connections for IPv4-only applications","114 KiB")
        package3 = manager.Package("9base","community","2-3","Port of various original Plan9 tools to unix","5.69 MiB")
        package4 = manager.Package("a2ps","extra","4.13c1","a2ps is an Any to PostScript filter","690 KiB")
        package5 = manager.Package("a52dec","extra","0.7.4-4","liba52 is a free library for decoding ATSC A/52 streams.","60 KiB")
        package6 = manager.Package("libcompizconfig","community","0.7.8-2","Compiz configuration system library","114 KiB")
        self.packages = [package1,package2,package3,package4,package5,package6]
        # begin wxGlade: MainFrame.__init__
        kwds["style"] = wx.DEFAULT_FRAME_STYLE
        wx.Frame.__init__(self, *args, **kwds)
        self.HorizontalSplitter = wx.SplitterWindow(self, -1, style=wx.SP_3D|wx.SP_BORDER)
        self.InfoTabs = wx.Notebook(self.HorizontalSplitter, -1, style=wx.NB_LEFT)
        self.VerticleSpitter = wx.SplitterWindow(self.HorizontalSplitter, -1, style=wx.SP_3D|wx.SP_BORDER)
        self.PackageGroupTabs = wx.Notebook(self.VerticleSpitter, -1, style=0)
        
        # Menu Bar
        self.MainWindow_menubar = wx.MenuBar()
        self.SetMenuBar(self.MainWindow_menubar)
        # Menu Bar end
        
        # Tool Bar
        self.MainWindow_toolbar = wx.ToolBar(self, -1, style=wx.TB_HORIZONTAL|wx.TB_TEXT|wx.TB_NOICONS)
        self.SetToolBar(self.MainWindow_toolbar)
        self.MainWindow_toolbar.AddLabelTool(wx.NewId(), "Reload", wx.NullBitmap, wx.NullBitmap, wx.ITEM_NORMAL, "", "")
        self.MainWindow_toolbar.AddLabelTool(wx.NewId(), "Mark All Upgrades", wx.NullBitmap, wx.NullBitmap, wx.ITEM_NORMAL, "", "")
        self.MainWindow_toolbar.AddLabelTool(wx.NewId(), "Apply", wx.NullBitmap, wx.NullBitmap, wx.ITEM_NORMAL, "", "")
        self.MainWindow_toolbar.AddSeparator()
        self.MainWindow_toolbar.AddLabelTool(wx.NewId(), "Properties", wx.NullBitmap, wx.NullBitmap, wx.ITEM_NORMAL, "", "")
        self.MainWindow_toolbar.AddSeparator()
        self.MainWindow_toolbar.AddLabelTool(wx.NewId(), "Search", wx.NullBitmap, wx.NullBitmap, wx.ITEM_NORMAL, "", "")
        # Tool Bar end
        self.RepoList = RepoList(self.PackageGroupTabs, 4, style=wx.LC_LIST|wx.LC_REPORT|wx.LC_NO_HEADER|wx.NO_BORDER)
        self.GroupList = wx.ListBox(self.PackageGroupTabs, -1, choices=[])
        self.StatusList = wx.ListBox(self.PackageGroupTabs, -1, choices=[])
        self.PackageList = PackageList(self.VerticleSpitter, -1, style=wx.LC_REPORT|wx.LC_VIRTUAL|wx.LC_SORT_ASCENDING|wx.SUNKEN_BORDER)
        self.InfoTextView = InfoTextView(self.InfoTabs, -1, "", style=wx.TE_MULTILINE|wx.TE_READONLY|wx.TE_RICH2|wx.TE_LINEWRAP)
        self.FeedbackTextView = wx.TextCtrl(self.InfoTabs, -1, "", style=wx.TE_MULTILINE|wx.TE_READONLY|wx.TE_LINEWRAP)
        self.FileTreeView = wx.TreeCtrl(self.InfoTabs, -1, style=wx.TR_HAS_BUTTONS|wx.TR_NO_LINES|wx.TR_DEFAULT_STYLE|wx.SUNKEN_BORDER)
        self.DependListView = wx.ListBox(self.InfoTabs, -1, choices=[])

        self.RepoList.SetRepositories(["all","core","community","extra","aur"])
        self.PackageList.SetPackages(self.packages)

        self.__set_properties()
        self.__do_layout()

        self.Bind(wx.EVT_LIST_ITEM_SELECTED, self.ResetFilters, self.RepoList)
        self.Bind(wx.EVT_LIST_ITEM_SELECTED, self.PackageSelected, self.PackageList)
        # end wxGlade

    def __set_properties(self):
        # begin wxGlade: MainFrame.__set_properties
        self.SetTitle("The Shwaurtz Package Manager")
        self.MainWindow_toolbar.SetToolBitmapSize((16, 15))
        self.MainWindow_toolbar.SetMargins((0, 0))
        self.MainWindow_toolbar.SetToolPacking(1)
        self.MainWindow_toolbar.SetToolSeparation(18)
        self.MainWindow_toolbar.Realize()
        self.PackageGroupTabs.SetMinSize((172, 352))
        self.VerticleSpitter.SetMinSize((729, 352))
        self.InfoTabs.SetMinSize((729, 207))
        self.HorizontalSplitter.SetMinSize((729, 564))
        # end wxGlade

    def __do_layout(self):
        # begin wxGlade: MainFrame.__do_layout
        Sizer = wx.BoxSizer(wx.VERTICAL)
        self.PackageGroupTabs.AddPage(self.RepoList, "Repo")
        self.PackageGroupTabs.AddPage(self.GroupList, "Groups")
        self.PackageGroupTabs.AddPage(self.StatusList, "Status")
        self.VerticleSpitter.SplitVertically(self.PackageGroupTabs, self.PackageList, 172)
        self.InfoTabs.AddPage(self.InfoTextView, "Information")
        self.InfoTabs.AddPage(self.FeedbackTextView, "Feedback")
        self.InfoTabs.AddPage(self.FileTreeView, "Files")
        self.InfoTabs.AddPage(self.DependListView, "Dependencies")
        self.HorizontalSplitter.SplitHorizontally(self.VerticleSpitter, self.InfoTabs)
        Sizer.Add(self.HorizontalSplitter, 1, wx.EXPAND, 0)
        self.SetSizer(Sizer)
        Sizer.Fit(self)
        self.Layout()
        # end wxGlade

    def PackageSelected(self, event): # wxGlade: MainFrame.<event_handler>
        self.PackageList.currentItem = event.m_itemIndex
        self.InfoTextView.SetPkgInfo(self.PackageList.packages[event.m_itemIndex])
        
    def ResetFilters(self, event): # wxGlade: MainFrame.<event_handler>
        self.PackageList.SetFilter([event.GetId(),event.GetText()])
        

# end of class MainFrame


