# -*- coding: utf-8 -*-
# generated by wxGlade 0.6.3 on Thu Feb 26 00:58:59 2009

import wx

# begin wxGlade: dependencies
# end wxGlade

# begin wxGlade: extracode
from PackageList import PackageList
from InfoTextView import InfoTextView
# end wxGlade

class MainFrame(wx.Frame):
    def __init__(self, *args, **kwds):
        # begin wxGlade: MainFrame.__init__
        kwds["style"] = wx.DEFAULT_FRAME_STYLE
        wx.Frame.__init__(self, *args, **kwds)
        self.HorizontalSplitter = wx.SplitterWindow(self, -1, style=wx.SP_3D|wx.SP_BORDER)
        self.InfoTabs = wx.Notebook(self.HorizontalSplitter, -1, style=wx.NB_LEFT)
        self.VerticleSpitter = wx.SplitterWindow(self.HorizontalSplitter, -1, style=wx.SP_3D|wx.SP_BORDER)
        self.PackageGroupTabs = wx.Notebook(self.VerticleSpitter, -1, style=0)
        
        # Menu Bar
        self.MainWindow_menubar = wx.MenuBar()
        self.SetMenuBar(self.MainWindow_menubar)
        # Menu Bar end
        
        # Tool Bar
        self.MainWindow_toolbar = wx.ToolBar(self, -1, style=wx.TB_HORIZONTAL|wx.TB_TEXT|wx.TB_NOICONS)
        self.SetToolBar(self.MainWindow_toolbar)
        self.MainWindow_toolbar.AddLabelTool(wx.NewId(), "Reload", wx.NullBitmap, wx.NullBitmap, wx.ITEM_NORMAL, "", "")
        self.MainWindow_toolbar.AddLabelTool(wx.NewId(), "Mark All Upgrades", wx.NullBitmap, wx.NullBitmap, wx.ITEM_NORMAL, "", "")
        self.MainWindow_toolbar.AddLabelTool(wx.NewId(), "Apply", wx.NullBitmap, wx.NullBitmap, wx.ITEM_NORMAL, "", "")
        self.MainWindow_toolbar.AddSeparator()
        self.MainWindow_toolbar.AddLabelTool(wx.NewId(), "Properties", wx.NullBitmap, wx.NullBitmap, wx.ITEM_NORMAL, "", "")
        self.MainWindow_toolbar.AddSeparator()
        self.MainWindow_toolbar.AddLabelTool(wx.NewId(), "Search", wx.NullBitmap, wx.NullBitmap, wx.ITEM_NORMAL, "", "")
        # Tool Bar end
        self.RepoList = wx.ListBox(self.PackageGroupTabs, -1, choices=[])
        self.GroupList = wx.ListBox(self.PackageGroupTabs, -1, choices=[])
        self.StatusList = wx.ListBox(self.PackageGroupTabs, -1, choices=[])
        self.PackageList = PackageList(self.VerticleSpitter, -1, style=wx.LC_REPORT|wx.LC_VIRTUAL|wx.LC_SORT_ASCENDING|wx.SUNKEN_BORDER)
        self.InfoTextView = InfoTextView(self.InfoTabs, -1, "", style=wx.TE_MULTILINE|wx.TE_READONLY|wx.TE_RICH2|wx.TE_LINEWRAP)
        self.FeedbackTextView = wx.TextCtrl(self.InfoTabs, -1, "", style=wx.TE_MULTILINE|wx.TE_READONLY|wx.TE_LINEWRAP)
        self.FileTreeView = wx.TreeCtrl(self.InfoTabs, -1, style=wx.TR_HAS_BUTTONS|wx.TR_NO_LINES|wx.TR_DEFAULT_STYLE|wx.SUNKEN_BORDER)
        self.DependListView = wx.ListBox(self.InfoTabs, -1, choices=[])

        self.__set_properties()
        self.__do_layout()

        self.Bind(wx.EVT_LIST_ITEM_SELECTED, self.package_selected, self.PackageList)
        # end wxGlade

    def __set_properties(self):
        # begin wxGlade: MainFrame.__set_properties
        self.SetTitle("The Shwaurtz Package Manager")
        self.MainWindow_toolbar.SetToolBitmapSize((16, 15))
        self.MainWindow_toolbar.SetMargins((0, 0))
        self.MainWindow_toolbar.SetToolPacking(1)
        self.MainWindow_toolbar.SetToolSeparation(18)
        self.MainWindow_toolbar.Realize()
        self.PackageGroupTabs.SetMinSize((172, 352))
        self.VerticleSpitter.SetMinSize((729, 352))
        self.InfoTabs.SetMinSize((729, 207))
        self.HorizontalSplitter.SetMinSize((729, 564))
        # end wxGlade

    def __do_layout(self):
        # begin wxGlade: MainFrame.__do_layout
        Sizer = wx.BoxSizer(wx.VERTICAL)
        self.PackageGroupTabs.AddPage(self.RepoList, "Repo")
        self.PackageGroupTabs.AddPage(self.GroupList, "Groups")
        self.PackageGroupTabs.AddPage(self.StatusList, "Status")
        self.VerticleSpitter.SplitVertically(self.PackageGroupTabs, self.PackageList, 172)
        self.InfoTabs.AddPage(self.InfoTextView, "Information")
        self.InfoTabs.AddPage(self.FeedbackTextView, "Feedback")
        self.InfoTabs.AddPage(self.FileTreeView, "Files")
        self.InfoTabs.AddPage(self.DependListView, "Dependencies")
        self.HorizontalSplitter.SplitHorizontally(self.VerticleSpitter, self.InfoTabs)
        Sizer.Add(self.HorizontalSplitter, 1, wx.EXPAND, 0)
        self.SetSizer(Sizer)
        Sizer.Fit(self)
        self.Layout()
        # end wxGlade

    def package_selected(self, event): # wxGlade: MainFrame.<event_handler>
        self.InfoTextView.set_pkg_info(self.PackageList.packages[event.m_itemIndex])
        self.PackageList.on_click(event)
        
# end of class MainFrame


