#!/usr/bin/env python
# -*- coding: utf-8 -*-
# generated by wxGlade 0.6.3 on Thu Feb 26 00:58:59 2009

import wx
from MainFrame import MainFrame

class Schwaurtz(wx.App):
    def OnInit(self):
        wx.InitAllImageHandlers()
        MainWindow = MainFrame(None, -1, "")
        self.SetTopWindow(MainWindow)
        MainWindow.Show()
        return 1

# end of class Schwaurtz

if __name__ == "__main__":
    Schwaurtz = Schwaurtz(0)
    Schwaurtz.MainLoop()
